# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt update

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt upgrade -y
          mkdir hello
          cd hello
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-386.tgz
          sudo tar xvzf ngrok-v3-stable-linux-386.tgz -C /usr/local/bin
          ngrok config add-authtoken 2IaMCj0QzC4SCS0ZTz5FLcNMcLi_4PdfzjjjL6Gcmc6P2tR9r
          wget https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.5.1/ant-media-server-community-2.5.1.zip
          wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh && chmod 755 install_ant-media-server.sh
          sudo ./install_ant-media-server.sh -i ant-media-server-community-2.5.1.zip
          sudo service antmedia stop
          sudo service antmedia start
          sudo service antmedia status
          ngrok http 127.0.0.1:5080
          echo "work done"
